Repository easifem/base, pull requests merged in 2024-05, with the labels that each got.

#306 updates in compile def
  CMakeLists.txt
  CMakePresets.json
  build.py
  cmake/addOpenMP.cmake
  install.py
  src/modules/GlobalData/src/GlobalData.F90
Labels: release

#312 Updates in Display methods
  src/modules/Display/src/Display_Method.F90
Labels: enhancement

#311 Updates in Lapack Utility
  src/modules/Lapack/src/GE_EigenValueMethods.F90
  src/submodules/Lapack/src/GE_EigenValueMethods@Methods.F90
Labels: enhancement, linalg

#313 Updates in EigenValueMethods
  release_install.py
  src/modules/Lapack/src/GE_EigenValueMethods.F90
  src/submodules/Lapack/src/GE_EigenValueMethods@Methods.F90
Labels: enhancement, linalg

#314 Updates in ReferenceElement_Method
  src/modules/GlobalData/src/GlobalData.F90
  src/submodules/Geometry/src/ReferenceElement_Method@ElementNameMethods.F90
  src/submodules/Geometry/src/ReferenceElement_Method@EnquireMethods.F90
  src/submodules/Geometry/src/ReferenceElement_Method@LocalNodeCoordsMethods.F90
  src/submodules/Geometry/src/ReferenceElement_Method@VTKMethods.F90
  src/submodules/Geometry/src/ReferenceQuadrangle_Method@Methods.F90
  src/submodules/Polynomial/src/QuadrangleInterpolationUtility@Methods.F90
Labels: enhancement, referenceElement
