Repository easifem/base, pull requests merged in 2024-01, with the labels that each got.

#277 Updates in ReferenceElement_Method
  src/submodules/Geometry/src/ReferenceElement_Method@FacetElementMethods.F90
Labels: enhancement, referenceElement

#281 Fixing bug in ReferenceQuad
  src/submodules/Geometry/src/ReferenceQuadrangle_Method@Methods.F90
Labels: referenceElement

#283 January release of easifem-base v23.10.3
  cmake/addOpenBLAS.cmake
  src/modules/BaseType/src/BaseType.F90
  src/modules/Geometry/src/ReferenceElement_Method.F90
  src/modules/MassMatrix/src/MassMatrix_Method.F90
  src/submodules/ElemshapeData/src/ElemshapeData_ConstructorMethods@Methods.F90
  src/submodules/ElemshapeData/src/H1/ElemshapeData_H1Methods@LagrangeMethods.F90
  src/submodules/Geometry/src/ReferenceElement_Method@FacetElementMethods.F90
  src/submodules/Geometry/src/ReferenceQuadrangle_Method@Methods.F90
  src/submodules/MassMatrix/src/MassMatrix_Method@Methods.F90
  src/submodules/STMassMatrix/src/STMassMatrix_Method@Methods.F90
Labels: release
